name: pq_dialog_flowtter
description: A Flutter implementation of DialogFlow improved. Get your chatbots ready in no time.
version: 1.0.0

environment:
    sdk: ">=2.12.0 <3.0.0"
    flutter: ">=1.17.0"

dependencies:
    flutter:
        sdk: flutter
    googleapis_auth: ^1.3.0
    equatable: ^2.0.0
    json_annotation: ^4.4.0
    meta: ^1.3.0
    http: ^1.2.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    effective_dart: ^1.3.0
    build_runner: ^2.1.7
    json_serializable: ^6.1.3
